# Generated by Django 5.2.10 on 2026-02-27 20:15

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class (e.g., bi-code-slash)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('featured_image', models.ImageField(help_text='16:9 ratio recommended (1200x675px)', upload_to='portfolio/featured/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, help_text='SEO: describe the image', max_length=150)),
                ('short_description', models.CharField(help_text='Brief 1-line description for cards', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Short tagline for project page', max_length=200)),
                ('full_description', ckeditor.fields.RichTextField(help_text='Main project description')),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('services_provided', models.CharField(blank=True, max_length=500)),
                ('project_duration', models.CharField(blank=True, max_length=100)),
                ('challenge', ckeditor.fields.RichTextField(blank=True, help_text="Describe the client's challenge")),
                ('approach', ckeditor.fields.RichTextField(blank=True, help_text='Describe your approach/strategy')),
                ('solution', ckeditor.fields.RichTextField(blank=True, help_text='Describe the final solution')),
                ('results', ckeditor.fields.RichTextField(blank=True, help_text='Describe measurable outcomes')),
                ('result_stat_1_label', models.CharField(blank=True, max_length=100)),
                ('result_stat_1_value', models.CharField(blank=True, max_length=50)),
                ('result_stat_2_label', models.CharField(blank=True, max_length=100)),
                ('result_stat_2_value', models.CharField(blank=True, max_length=50)),
                ('result_stat_3_label', models.CharField(blank=True, max_length=100)),
                ('result_stat_3_value', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.category')),
                ('technologies', models.ManyToManyField(blank=True, to='portfolio.technology')),
            ],
            options={
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-published_at', 'status'], name='portfolio_p_publish_c5c65c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_e96b08_idx'),
        ),
    ]
